import {
	CANVAS_LINKS,
	FIRST_DAY_OF_SCHOOL,
	SCHEDULES,
	SCHOOL_HOLIDAYS,
	SCHOOL_START_COLOR,
} from "./data";
import { main } from "./lib";

main(
	new Date(),
	SCHOOL_HOLIDAYS,
	SCHEDULES,
	FIRST_DAY_OF_SCHOOL,
	SCHOOL_START_COLOR,
	CANVAS_LINKS
);
